[package]
name = "rustyract"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
c = { package = "tesseract-ocr-static-c", path = "c" }

[dev-dependencies]
image = "0.25.9"

[workspace]
members = [".", "cli", "c"]
default-members = [".", "cli", "c"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lints.clippy]
unwrap_used = "deny"
