[package]
name = "rustyract"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
fs = { package = "fs-err", version = "3.3.0" }
jobserver = "0.1.34"

[dev-dependencies]
image = "0.25.9"

[workspace]
members = [".", "cli"]
default-members = [".", "cli"]

[lints.clippy]
unwrap_used = "deny"
