#![doc = include_str!("../README.md")]

mod c;

pub use self::c::{
    ETEXT_DESC, PIX, TessBaseAPI, TessBaseAPIAnalyseLayout, TessBaseAPIClear,
    TessBaseAPIClearAdaptiveClassifier, TessBaseAPIClearPersistentCache, TessBaseAPICreate,
    TessBaseAPIDelete, TessBaseAPIEnd, TessBaseAPIGetAltoText, TessBaseAPIGetBoolVariable,
    TessBaseAPIGetBoxText, TessBaseAPIGetDatapath, TessBaseAPIGetDoubleVariable,
    TessBaseAPIGetGradient, TessBaseAPIGetHOCRText, TessBaseAPIGetIntVariable,
    TessBaseAPIGetIterator, TessBaseAPIGetLSTMBoxText, TessBaseAPIGetPAGEText,
    TessBaseAPIGetPageSegMode, TessBaseAPIGetStringVariable, TessBaseAPIGetTextDirection,
    TessBaseAPIGetThresholdedImage, TessBaseAPIGetThresholdedImageScaleFactor,
    TessBaseAPIGetTsvText, TessBaseAPIGetUNLVText, TessBaseAPIGetUTF8Text,
    TessBaseAPIGetWordStrBoxText, TessBaseAPIInit2, TessBaseAPIInitForAnalysePage,
    TessBaseAPIIsValidWord, TessBaseAPIOem, TessBaseAPIPrintVariablesToFile, TessBaseAPIRecognize,
    TessBaseAPISetDebugVariable, TessBaseAPISetImage2, TessBaseAPISetMinOrientationMargin,
    TessBaseAPISetPageSegMode, TessBaseAPISetRectangle, TessBaseAPISetSourceResolution,
    TessBaseAPISetVariable, TessChoiceIterator, TessChoiceIteratorConfidence,
    TessChoiceIteratorDelete, TessChoiceIteratorGetUTF8Text, TessChoiceIteratorNext,
    TessDeleteText, TessMonitorCreate, TessMonitorDelete, TessMonitorGetProgress,
    TessMonitorSetCancelFunc, TessMonitorSetCancelThis, TessMonitorSetDeadlineMSecs,
    TessMonitorSetProgressFunc, TessOcrEngineMode_OEM_DEFAULT, TessOcrEngineMode_OEM_LSTM_ONLY,
    TessOcrEngineMode_OEM_TESSERACT_LSTM_COMBINED, TessOcrEngineMode_OEM_TESSERACT_ONLY,
    TessOrientation_ORIENTATION_PAGE_DOWN, TessOrientation_ORIENTATION_PAGE_LEFT,
    TessOrientation_ORIENTATION_PAGE_RIGHT, TessOrientation_ORIENTATION_PAGE_UP, TessPageIterator,
    TessPageIteratorBaseline, TessPageIteratorBegin, TessPageIteratorBlockType,
    TessPageIteratorBoundingBox, TessPageIteratorCopy, TessPageIteratorDelete,
    TessPageIteratorGetBinaryImage, TessPageIteratorGetImage, TessPageIteratorIsAtBeginningOf,
    TessPageIteratorIsAtFinalElement, TessPageIteratorLevel_RIL_BLOCK,
    TessPageIteratorLevel_RIL_PARA, TessPageIteratorLevel_RIL_SYMBOL,
    TessPageIteratorLevel_RIL_TEXTLINE, TessPageIteratorLevel_RIL_WORD, TessPageIteratorNext,
    TessPageIteratorOrientation, TessPageIteratorParagraphInfo, TessPageSegMode_PSM_AUTO,
    TessPageSegMode_PSM_AUTO_ONLY, TessPageSegMode_PSM_AUTO_OSD, TessPageSegMode_PSM_CIRCLE_WORD,
    TessPageSegMode_PSM_OSD_ONLY, TessPageSegMode_PSM_RAW_LINE, TessPageSegMode_PSM_SINGLE_BLOCK,
    TessPageSegMode_PSM_SINGLE_BLOCK_VERT_TEXT, TessPageSegMode_PSM_SINGLE_CHAR,
    TessPageSegMode_PSM_SINGLE_COLUMN, TessPageSegMode_PSM_SINGLE_LINE,
    TessPageSegMode_PSM_SINGLE_WORD, TessPageSegMode_PSM_SPARSE_TEXT,
    TessPageSegMode_PSM_SPARSE_TEXT_OSD, TessParagraphJustification_JUSTIFICATION_CENTER,
    TessParagraphJustification_JUSTIFICATION_LEFT, TessParagraphJustification_JUSTIFICATION_RIGHT,
    TessParagraphJustification_JUSTIFICATION_UNKNOWN, TessPolyBlockType_PT_CAPTION_TEXT,
    TessPolyBlockType_PT_EQUATION, TessPolyBlockType_PT_FLOWING_IMAGE,
    TessPolyBlockType_PT_FLOWING_TEXT, TessPolyBlockType_PT_HEADING_IMAGE,
    TessPolyBlockType_PT_HEADING_TEXT, TessPolyBlockType_PT_HORZ_LINE,
    TessPolyBlockType_PT_INLINE_EQUATION, TessPolyBlockType_PT_NOISE,
    TessPolyBlockType_PT_PULLOUT_IMAGE, TessPolyBlockType_PT_PULLOUT_TEXT,
    TessPolyBlockType_PT_TABLE, TessPolyBlockType_PT_UNKNOWN, TessPolyBlockType_PT_VERT_LINE,
    TessPolyBlockType_PT_VERTICAL_TEXT, TessProgressFunc, TessResultIterator,
    TessResultIteratorConfidence, TessResultIteratorCopy, TessResultIteratorDelete,
    TessResultIteratorGetChoiceIterator, TessResultIteratorGetPageIterator,
    TessResultIteratorGetUTF8Text, TessResultIteratorNext, TessResultIteratorSymbolIsDropcap,
    TessResultIteratorSymbolIsSubscript, TessResultIteratorSymbolIsSuperscript,
    TessResultIteratorWordFontAttributes, TessResultIteratorWordIsFromDictionary,
    TessResultIteratorWordIsNumeric, TessResultIteratorWordRecognitionLanguage,
    TessTextlineOrder_TEXTLINE_ORDER_LEFT_TO_RIGHT, TessTextlineOrder_TEXTLINE_ORDER_RIGHT_TO_LEFT,
    TessTextlineOrder_TEXTLINE_ORDER_TOP_TO_BOTTOM, TessVersion,
    TessWritingDirection_WRITING_DIRECTION_LEFT_TO_RIGHT,
    TessWritingDirection_WRITING_DIRECTION_RIGHT_TO_LEFT,
    TessWritingDirection_WRITING_DIRECTION_TOP_TO_BOTTOM, getLeptonicaVersion, pixClone, pixCreate,
    pixDestroy, pixGetData, pixGetDimensions, pixGetHeight, pixGetWidth, pixGetWpl,
};
