---
name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo -n apt-get update -qq && sudo -n apt-get install -qqy nasm clang-20 lld-20 llvm-20
      - name: Test
        env:
          RUST_BACKTRACE: 1
          CC: clang-20
          CXX: clang++-20
          LIBCLANG_PATH: /usr/lib/llvm-20/lib
          LIBCLANG_INCLUDE: /usr/lib/llvm-20/lib/clang/20/include
        run: ./ci/test.sh
