---
name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo -n apt-get update -qq && sudo -n apt-get install -qqy nasm
      - name: Test
        env:
          RUST_BACKTRACE: 1
        run: ./ci/test.sh
